### ISSUE TITLE
Issue with multiple image download

### ISSUE THREAD

**Issue by ArneBanck** [biesiad/jquery-multidownload#21]
Hi,

I am trying to download multiple jpeg files with your plugin but it seems to interpret the image as a document. I get the following error in chrome console element : Resource interpreted as Document but transferred with MIME type image/jpeg:
Is there a way to treat the images as a image/jpeg with your plugin?

Greetings

**Comment by biesiad** [comment]
The plugin creates temporary iframe to trigger the downloads. Probably that's why it treats the files as documents. This is not an issue if you try to download pdf files (which I was doing when I wrote this code). I'd experiment with [download](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) attribute of `a` element to get around your issue.
